create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number integer generated by default as identity (start with 100 increment by 1) unique not null,
  customer_name text not null default 'Customer',
  coffee_id text,
  coffee_name text,
  coffee_price numeric(10, 2),
  dessert_id text,
  dessert_name text,
  dessert_price numeric(10, 2),
  total numeric(10, 2) not null default 0,
  status text not null default 'waiting' check (status in ('waiting', 'serving', 'done')),
  created_at timestamptz not null default now(),
  items jsonb,
  payment_method text not null default 'Cash' check (payment_method in ('Cash', 'GCash', 'Card')),
  payment_status text not null default 'Not Paid' check (payment_status in ('Not Paid', 'Paid'))
);

alter table public.orders enable row level security;
alter table public.orders replica identity full;

drop policy if exists "Public can read cafe orders" on public.orders;
drop policy if exists "Public can create cafe orders" on public.orders;
drop policy if exists "Public can update cafe order status" on public.orders;

create policy "Public can read cafe orders"
on public.orders for select
to anon
using (true);

create policy "Public can create cafe orders"
on public.orders for insert
to anon
with check (true);

create policy "Public can update cafe order status"
on public.orders for update
to anon
using (true)
with check (status in ('waiting', 'serving', 'done'));

do $$
begin
  alter publication supabase_realtime add table public.orders;
exception
  when duplicate_object then null;
end $$;

-- 3. Gawaing table para sa syncable products menu items
create table if not exists public.products (
  id text primary key,
  name text not null,
  price numeric(10, 2) not null,
  note text,
  image text,
  alt text,
  tag text,
  pairing text,
  category text not null check (category in ('coffee', 'dessert')),
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.products replica identity full;

drop policy if exists "Public can read products" on public.products;
drop policy if exists "Public can create/update products" on public.products;

create policy "Public can read products"
on public.products for select
to anon
using (true);

create policy "Public can create/update products"
on public.products for all
to anon
using (true);

do $$
begin
  alter publication supabase_realtime add table public.products;
exception
  when duplicate_object then null;
end $$;